AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
    Description: Project name that will be used to name and identify resoures that are created
    Default: vpnDemo
  KeyName:
    Type: String
    Description: SSH keypair to use to access 1000v
    Default: cjl-aws-mac

Resources:

  ################### Create VPC to work within ###################

  vpc:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        -
          Key: ProjectName
          Value: !Ref ProjectName
        -
          Key: Name
          Value: !Ref ProjectName
      TemplateURL: https://s3.amazonaws.com/cjl-cloudformation-stack-templates/vpc.yaml

  vpnServer:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        -
          Key: ProjectName
          Value: !Ref ProjectName
        -
          Key: Name
          Value: !Ref ProjectName
      TemplateURL: https://s3.amazonaws.com/policedemo-cf-templates/vpn/vpnSwan.yaml
      Parameters:
        TestVPNServerKeyPair: !Ref KeyName
        vpcId: !GetAtt vpc.Outputs.vpcId
        PublicSubnetDMZ1: !GetAtt vpc.Outputs.subnetAId

        #Outputs:
        #  SshAccessToCSR:
        #    Description: The EIP of the CSR
        #    Value: !Ref eip
