AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
    Description: Project name that will be used to name and identify resoures that are created
    Default: vpnDemo
  KeyName:
    Type: String
    Description: SSH keypair to use to access 1000v
    Default: cjl-aws-mac
Mappings:
  RegionMap:
    eu-central-1:
      "64": "ami-9a91b371"
    eu-west-1:
      "64": "ami-ca0135b3"
    eu-west-2:
      "64": "ami-c12dcda6"
    eu-west-3:
      "64": "ami-cae150b7"
    sa-east-1:
      "64": "ami-f09dcc9c"
    us-east-2:
      "64": "ami-976152f2"
    us-east-1:
      "64": "ami-467ca739"
    us-west-1:
      "64": "ami-46e1f226"
    us-west-2:
      "64": "ami-e251209a"
    ap-northeast-1:
      "64": "ami-92df37ed"
    ap-northeast-2:
      "64": "ami-efaf0181"
    ap-northeast-3:
      "64": "ami-b4faf4c9"
    ap-south-1:
      "64": "ami-b46f48db"
    ap-southeast-1:
      "64": "ami-de90a5a2"
    ap-southeast-2:
      "64": "ami-60a26a02"
    ca-central-1:
      "64": "ami-338a0a57"

Resources:

  ################### Create VPC to work within ###################

  vpc:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        -
          Key: ProjectName
          Value: !Ref ProjectName
        -
          Key: Name
          Value: !Ref ProjectName
      TemplateURL: https://s3.amazonaws.com/cjl-cloudformation-stack-templates/vpc.yaml

  cisco1000v:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        KeyName: !Ref KeyName
        CidrIp1: 0.0.0.0/0
        CidrIp2: 0.0.0.0/0
        SubnetPublic: !GetAtt vpc.Outputs.subnetAId
        SubnetPrivate: !GetAtt vpc.Outputs.privateSubnetAId
        VPC: !GetAtt vpc.Outputs.vpcId
      Tags:
        -
          Key: ProjectName
          Value: !Ref ProjectName
        -
          Key: Name
          Value: !Ref ProjectName
      TemplateURL: https://s3.amazonaws.com/cjl-cloudformation-stack-templates/cisco1000v.yaml

  privateTestInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.nano
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          #GroupSet:
          #  - !Ref securityGroup
          SubnetId: !GetAtt vpc.Outputs.privateSubnetAId
          #UserData:
          #  Fn::Base64: !Sub |
          #    #!/bin/bash
          #    yum install -y httpd
          #    service httpd start
          #    chkconfig httpd on
          #    echo $(hostname) > /var/www/html/index.html
      Tags:
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Name
        Value: Test VPN instance

  eip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  AssociateEip:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt eip.AllocationId
      NetworkInterfaceId: !GetAtt cisco1000v.Outputs.csrInterfaceId

Outputs:
  SshAccessToCSR:
    Description: The EIP of the CSR
    Value: !Ref eip
