AWSTemplateFormatVersion: "2010-09-09"
  
Description: "This cloudformation stack uses nested templates to deploy a cloud enviroment that can be used to mimic a customers on prem enviroment.  This can then be used to demonstrate how AWS services can integrate with on premise enviroments such as creating an VPN to connect the two or extending an existing Active Directory into AWS."

Parameters:
  ProjectName:
    Description: Name to tag resources with
    Type: String
    Default: glue-demo

Mappings:                              
  RegionMap:                           
    eu-central-1:                      
      "64": "ami-9a91b371"             
    eu-west-1:                         
      "64": "ami-0fad7378adf284ce0"    
    eu-west-2:                         
      "64": "ami-0664a710233d7c148"    
    eu-west-3:                         
      "64": "ami-cae150b7"             
    sa-east-1:                         
      "64": "ami-f09dcc9c"             
    us-east-2:                         
      "64": "ami-976152f2"             
    us-east-1:                         
      "64": "ami-467ca739"             
    us-west-1:                         
      "64": "ami-46e1f226"             
    us-west-2:                         
      "64": "ami-e251209a"             
    ap-northeast-1:                    
      "64": "ami-92df37ed"             
    ap-northeast-2:                    
      "64": "ami-efaf0181"             
    ap-northeast-3:                    
      "64": "ami-b4faf4c9"             
    ap-south-1:                        
      "64": "ami-b46f48db"             
    ap-southeast-1:                    
      "64": "ami-de90a5a2"             
    ap-southeast-2:                    
      "64": "ami-60a26a02"             
    ca-central-1:                      
      "64": "ami-338a0a57"             

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/aws-shared-demo-cf-templates/vpc/vpc-1.yaml
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Name
          Value: !Ref ProjectName
      Parameters:
        ProjectName: !Ref ProjectName

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead

Resources:                                                                                         
  securityGroup:                                                                                   
    Type: AWS::EC2::SecurityGroup                                                                  
    Properties:                                                                                    
      GroupDescription: Allow SSH to VPN server                                                    
      VpcId: !Ref vpcId                                                                            
      SecurityGroupIngress:                                                                        
      - IpProtocol: tcp                                                                            
        FromPort: '22'                                                                             
        ToPort: '22'                                                                               
        CidrIp: 0.0.0.0/0                                                                          
                                                                                                   
  insecureHost1:                                                                                          
    Type: "AWS::EC2::Instance"                                                                     
    Properties:                                                                                    
      InstanceType: t2.nano                                                                        
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]                                      
      NetworkInterfaces:                                                                           
        - AssociatePublicIpAddress: "true"                                                         
          DeviceIndex: "0"                                                                         
          GroupSet:                                                                                
            - !Ref securityGroup                                                                   
          SubnetId: !GetAtt vpc.Outputs.subnetBId
      UserData:                                                                                    
        "Fn::Base64":                                                                              
          !Sub |                                                                                   
            #!/bin/bash        
            while true ; do                                                                    
              curl -s http://com.minergate.pool/dkjdjkjdlsajdkljalsskajdksakjdksajkllalkdjsalkjdsalkjdlkasj  > /dev/null &
              curl -s http://xdn-xmr.pool.minergate.com/dhdhjkhdjkhdjkhajkhdjskahhjkhjkahdsjkakjasdhkjahdjk  > /dev/null &                                                                                             
              dig -f ./domains/queries.txt > /dev/null &
              dig GuardDutyC2ActivityB.com any
              sleep 5
            done
      Tags:                                                                                        
       - Key: Name                                                                                 
         Value: Insecure-host-1
